services:
  - type: web
    name: pdf-anonymizer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://openrouter.ai/api/v1
      - key: FRONTEND_URL
        sync: false 